export const GET_COINS_START = 'GET_COINS_START';
export const GET_COINS_SUCCESS = 'GET_COINS_SUCCESS';
export const GET_COINS_FAIL = 'GET_COINS_FAIL';
export const GET_PRICE_HISTORY_START = 'GET_PRICE_HISTORY_START';
export const GET_PRICE_HISTORY_SUCCESS = 'GET_PRICE_HISTORY_SUCCESS';
export const GET_PRICE_HISTORY_FAIL = 'GET_PRICE_HISTORY_FAIL';
